name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Get Environment (Development)
        if: github.ref != 'refs/heads/master' && !contains(github.ref, '/rl-')
        run: |
          echo "buildConfiguration=Debug" >> $GITHUB_ENV
      - name: Get Environment (Production)
        if: github.ref == 'refs/heads/master' || contains(github.ref, '/rl-')
        run: |
          echo "buildConfiguration=Release" >> $GITHUB_ENV
      - name: Build
        run: |
          dotnet build src/BWHazel.Data.TypedId.sln
      - name: Test
        run: |
          dotnet test src/BWHazel.Data.TypedId.sln
      - name: Pack
        run: |
          dotnet pack src/BWHazel.Data.TypedId.sln -c ${{ env.buildConfiguration }} -o dist
      - name: Upload Build Artefact
        uses: actions/upload-artifact@v3
        with:
          name: typed-id
          path: dist
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, '/rl-')
    steps:
      - name: Download Build Artefact
        uses: actions/download-artifact@v3
        with:
          name: typed-id
          path: dist
      - name: Publish to NuGet
        run: |
          dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json